name: Download binary assets
description: Downloads the provider and tfgen binaries to `bin/`.

runs:
  using: "composite"
  steps:
    - name: Download provider + tfgen binaries
      uses: actions/download-artifact@v4
      with:
        name: pulumiservice-provider.tar.gz
        path: ${{ github.workspace }}/bin
    - name: Untar provider binaries
      shell: bash
      # TODO: Assumes `bin` directory. Should this be a `make` target?
      run: |
        tar -zxf ${{ github.workspace }}/bin/provider.tar.gz -C ${{ github.workspace}}/bin
        find ${{ github.workspace }} -name "pulumi-*-pulumiservice" -print -exec chmod +x {} \;
